baseURL = 'https://deciphr.github.io/'
languageCode = 'en-us'
title = 'deciphr'
theme = "idyllic"

enableEmoji = true
summaryLength = 7

[params]
  enableSummary = false
  [params.whoami]
    descriptor = 'a cybersecurity student interested in'
    focus = 'industrial control systems + hardware'
  [params.socials]
    github = 'https://github.com/deciphr'
  [params.tagcolors]
    pwn = '#4c00b0'
    rev = '#e6b400'
    web = '#228b22'
    forensics = '#4169e1'

[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    style = "modus-vivendi"
