baseURL = 'https://deciphr.github.io/'
languageCode = 'en-us'
title = 'deciphr'
theme = 'holy'

[menu]
[[menu.main]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/deciphr"
    weight = 10
