baseURL = 'https://deciphr.github.io/'
enableEmoji = true
languageCode = 'en-us'
title = 'deciphr'
theme = 'holy'

[params]
    copyright = "© deciphr"

[markup]
    [markup.highlight]
        noClasses = false

[menu]
    [[menu.main]]
        identifier = "github"
        name = "GitHub"
        url = "https://github.com/deciphr"
        weight = 10

    [[menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/blog"
        weight = 9

    [[menu.main]]
        identifier = "writeups"
        name = "Writeups"
        url = "/writeups"
        weight = 8

[taxonomies]
    tag = 'tags'
